[sdsl_lite]
git-tree-sha1 = "094e9feb71cad749fa0719c442f4e1b0d018dbc8"

    [[sdsl_lite.download]]
    sha256 = "82ebd440cc00e038a5279de275487ecdb25646d0bed283bab17e73a351f91e8c"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v3.0.3+0/sdsl_lite.v3.0.3.any.tar.gz"
