[[sdsl_lite]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "113acc8b236a892896ff45ef89c2ae5b5f5dac9b"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "9085bb9e5ebd5515a69980d8a9f5d2b4b83503fbcc640e50a78d5b6447a4c156"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[sdsl_lite]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab59193a4bd6481dd86d646e9968daba316e7d03"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "b332186dd6646a633a7d8f79a1fa6b83436e59295a907b9dae518704d69a7db6"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[sdsl_lite]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "962a1e6c55cd869a2cc759a8ae1cdc205d959196"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "fae401e80f3eae0e1bde564edcf80148d929490ef5706a0e2274b265fcca2322"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2599f87aca6bab74bbacc6f894175831ca837390"
os = "freebsd"

    [[sdsl_lite.download]]
    sha256 = "e53dc50241bb2e948234dc4a9ef886df6fcd0ca0f7cc69fcf44b3f0641228d13"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[sdsl_lite]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28274c2d24ca7666a671e2522f2abdf816de4f46"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "494686224df823da5784fd151849e41a1a29a4842eeaf038ec0e3b7fbcddae84"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.arm-linux-musleabihf-cxx03.tar.gz"
[[sdsl_lite]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1c55241bf11aa82590022bffb7ed145f4a33c8ac"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "39e926d7287edf4b122961cf96033ec1a8454bfba08ec5026afb4db1bd73cffd"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.i686-linux-musl-cxx03.tar.gz"
[[sdsl_lite]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "626ea1f847b0b7cf8dc429c2c51d59b33288b986"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "8ec1f46f4c1b8526770d5c0cad9065812db08c2f0976250c8d8fd98f6a364273"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[sdsl_lite]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eb5dd01249cc61c9021435c41b0368467fbabcdc"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "35a94cff4c642cee71eece9831b6c7351e5ded624ac81617328e50a0725819f3"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.arm-linux-gnueabihf-cxx03.tar.gz"
[[sdsl_lite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae7561c083f123e9830d8b3be6a6e77d6d90335f"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "fdf426fdd8f3060aeebc78d9d7da5ecd7f9ce63e4c572c5e29d38c88c825c942"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.i686-linux-gnu-cxx11.tar.gz"
[[sdsl_lite]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86b97a6f56a0fe4855977e331f14596077f1f234"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "44878bbba740772c827586834f965be00061037032a02757f45457e3e4957e5a"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[sdsl_lite]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e91a197b9ca9a3be3cb5b2a258e498560b4965a8"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "1d6c29d1f4005876f15d78ad30f10d495e35d16caba461dbe447a6203110b6ea"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.arm-linux-musleabihf-cxx11.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95e67f80424246b9cf0add4b4cffc6958224afcc"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "25dea189845d753350ece39a15f6044feeff09d24f8122cab061dc56038b3267"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[sdsl_lite]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4ed278f33ca9fcf524fb1a81e4a5e11c3b32912"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "fc2b98151dd974ab07683a6f8e0bdb297ac83d984ce1a1adc3bb65b9dd3a52d8"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.i686-linux-gnu-cxx03.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e84da65156cda3350688c3a2b24fce477d67bd9f"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "4da66e3557286fbd353e643563821036a04af590ad5c69511ca5bac3f28840fc"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9aed3719bc15ce3e81817f7501ce12767dad977d"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "ff42112bec26045a68608223317b74e0da9cd8f419f8e299cf4faf9e1c46c95f"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0eff91c28a7d763dff2c79b6a2ae44f4e218b1ba"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "c4b24ce7002a56006750218ddb86afaaf83e3f4fae9f466a254cc32b2b7fc1a5"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[sdsl_lite]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a94fd0049d33847d34a83be18fab34971370e4c3"
libc = "musl"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "336ced437564c6a28a0e45a00bda90ce044195a12f1f495a96a4e4ca7748db65"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.i686-linux-musl-cxx11.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9630ebed2b60254b782c5979596ea09d42a8275e"
os = "macos"

    [[sdsl_lite.download]]
    sha256 = "edca021887e74d61959e55e38c094a404dcd1442fc4f5d6fe265a06c461be9c7"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[sdsl_lite]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b7f81b892768fe0340fd23fdfa6e7b1c48c53ff"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "b70c3b3afb4f43bc0609599d83d36afad74514c648d15ea6e110198fe33c9a35"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788787b1383106af5c98f57c5922c790c1db9678"
os = "macos"

    [[sdsl_lite.download]]
    sha256 = "aaca69773e58f8b249c485e98bc8003624e43c601668a2571148675fcf68c996"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[sdsl_lite]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1a584206a023bfa81aaa70beafea86b7278c8aa"
libc = "glibc"
os = "linux"

    [[sdsl_lite.download]]
    sha256 = "6e8ffffe4ee078cff318be25fef2a41d49275f6c7bbec892da25cd4d441ff334"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.arm-linux-gnueabihf-cxx11.tar.gz"
[[sdsl_lite]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde7b375eaf285ef80caf92fd8f582e3d3bbf9b7"
os = "freebsd"

    [[sdsl_lite.download]]
    sha256 = "6e608048dab98f5e853dd596d90a7ac37d5a79bf57eac4f2c03be0d7be86f354"
    url = "https://github.com/JuliaBinaryWrappers/sdsl_lite_jll.jl/releases/download/sdsl_lite-v2.1.1+0/sdsl_lite.v2.1.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
