# Autogenerated wrapper script for sdsl_lite_jll for any
JLLWrappers.@generate_wrapper_header("sdsl_lite")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
